### ISSUE TITLE
Change install scripts to not use force-yes

### ISSUE THREAD

**Issue by thenor** [Pelagicore/vagrant-cookbook#3]
The install shell scripts use the flag "force-yes" which is deprecated in apt-get, but there is no other obvious or recommended substitute since we need a solution which is non-interactive (something which forces installation, but never prompts for input). "assume-yes" results in not all dependencies being installed, "allow" flags may prompt for input.
Replace all "force-yes" occurrences.

**Comment by sashko** [comment]
@thenor could you please update the status of this issue?

**Comment by thenor** [comment]
I can't find that we are using force-yes anymore so most likely this has been fixed at some point.
