### ISSUE TITLE
Scripts on yocto fail when calling other scripts

### ISSUE THREAD

**Issue by fhajredini** [Pelagicore/vagrant-cookbook#77]
Right now, scripts such as `fetch-sources-for-recipes.sh` fail to find other scripts when calling them. This is because the actual scripts can only be called from the pelux-manifests repository under yocto.groovy. 

I believe the commit "Replace duplicated code with init bitbake script" should be reverted

**Comment by frznlogic** [comment]
@fhajredini should this issue be closed with the #78 PR?

**Comment by thenor** [comment]
@frznlogic Yes, I think so also. Let's await Fisnik's response.

**Comment by fhajredini** [comment]
This has been fixed.
